# Generated by Django 4.0.2 on 2022-02-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project_title', models.CharField(max_length=50)),
                ('project_description', models.CharField(max_length=250)),
                ('project_technology', models.CharField(max_length=50)),
                ('estimatedHours', models.IntegerField()),
            ],
            options={
                'db_table': 'project_detail',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('projectdetail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectdetail')),
                ('user1_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.user1')),
            ],
            options={
                'db_table': 'project_team',
            },
        ),
        migrations.CreateModel(
            name='ProjectModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('project_module_name', models.CharField(max_length=100)),
                ('project_module_description', models.CharField(max_length=250)),
                ('estimatedHours', models.IntegerField()),
                ('projectdetail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectdetail')),
            ],
            options={
                'db_table': 'project_module',
            },
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.status'),
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority_level', models.CharField(max_length=20)),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.status')),
            ],
            options={
                'db_table': 'priorirty',
            },
        ),
    ]
