# Generated by Django 4.0.2 on 2022-03-30 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_status_id_priority_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectteam',
            old_name='projectdetail_id',
            new_name='projectdetail',
        ),
        migrations.RenameField(
            model_name='projectteam',
            old_name='user1_id',
            new_name='user1',
        ),
    ]
