# Generated by Django 4.0.2 on 2022-02-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('task_title', models.CharField(max_length=50)),
                ('projectdetail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectdetail')),
                ('projectmodule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.projectmodule')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.priority')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.user1')),
            ],
            options={
                'db_table': 'user_task',
            },
        ),
    ]
