# Generated by Django 4.0.2 on 2022-04-27 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_subtask'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subtask',
            table='sub_task',
        ),
    ]
