# Generated by Django 4.0.2 on 2022-03-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_role_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='User_Role',
        ),
    ]
